# Generated by Django 5.0 on 2024-04-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='slug',
        ),
        migrations.AlterField(
            model_name='chat',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Тема диалога'),
        ),
    ]
