# Generated by Django 5.0 on 2024-08-11 10:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userfavorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorites',
            name='favorites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
