# Generated by Django 5.0 on 2024-08-05 13:11

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0018_alter_element_options_alter_elementtwo_options_and_more'),
        ('main_page_domer', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reasonofcomplaint',
            options={'ordering': ['id'], 'verbose_name': 'Причина жалобы', 'verbose_name_plural': 'Причины жалобы'},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='category',
        ),
        migrations.AddField(
            model_name='publication',
            name='announcement',
            field=django_ckeditor_5.fields.CKEditor5Field(default=' ', verbose_name='Аннотация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Прошло модерацию'),
        ),
        migrations.AddField(
            model_name='publication',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.advertisement', verbose_name='Объявление, на которое пожаловались'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.TextField(verbose_name='Обоснование жалобы'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Пользователь, отправивший жалобу'),
        ),
        migrations.AlterField(
            model_name='photopublication',
            name='photo',
            field=models.ImageField(upload_to='images/publications', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='preview_image',
            field=models.ImageField(upload_to='images/publications', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='main_page_d_search__89e051_gin'),
        ),
    ]
