# Generated by Django 5.0 on 2024-03-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Прошло модерацию'),
        ),
    ]
