# Generated by Django 5.0 on 2024-08-10 15:22
# Generated by Django 5.0 on 2024-08-10 15:23

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0003_alter_reasonofcomplaint_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст помощи')),
            ],
            options={
                'verbose_name': 'Текст страницы помощь',
                'verbose_name_plural': 'Текст страницы помощь',
            },
        ),
        migrations.AlterField(
            model_name='publication',
            name='preview_image',
            field=models.ImageField(upload_to='images/publications/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
