# Generated by Django 5.0 on 2024-03-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0003_publication_moderated'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='announcement',
            field=models.TextField(default=1, verbose_name='Анонс'),
            preserve_default=False,
        ),
    ]
