# Generated by Django 5.0 on 2024-03-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0004_publication_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='preview_image',
            field=models.ImageField(upload_to='images/publications', verbose_name='Главная фотография'),
        ),
    ]
