# Generated by Django 5.0 on 2024-08-12 08:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0004_help_alter_publication_preview_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='search_title_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_title_vector'], name='main_page_d_search__18576a_gin'),
        ),
    ]
