# Generated by Django 5.0 on 2024-03-25 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0005_alter_publication_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='preview_image',
        ),
        migrations.CreateModel(
            name='ImagesForPublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/publications', verbose_name='Фото')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page_domer.publication', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Фото публикации',
                'verbose_name_plural': 'Фото публикаций',
                'ordering': ['-id'],
            },
        ),
    ]
