# Generated by Django 5.0 on 2024-03-27 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0006_remove_publication_preview_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesforpublications',
            name='advertisement',
        ),
        migrations.AddField(
            model_name='imagesforpublications',
            name='publications',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_page_domer.publication', verbose_name='Публикация'),
            preserve_default=False,
        ),
    ]
