# Generated by Django 5.0 on 2024-03-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0007_remove_imagesforpublications_advertisement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagesForPublications',
        ),
    ]
