# Generated by Django 5.0 on 2024-03-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0008_delete_imagesforpublications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopublication',
            name='photo',
            field=models.ImageField(upload_to='images/publications', verbose_name='Фото'),
        ),
    ]
