# Generated by Django 5.0 on 2024-03-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0009_alter_photopublication_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photopublication',
            old_name='publication',
            new_name='publications',
        ),
    ]
