# Generated by Django 5.0 on 2024-04-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0011_publication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='category',
        ),
        migrations.AddField(
            model_name='publication',
            name='preview_image',
            field=models.ImageField(default=1, upload_to='images/publications', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
