# Generated by Django 5.0 on 2024-05-06 22:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0012_remove_publication_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='announcement',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст статьи'),
        ),
    ]
