# Generated by Django 5.0 on 2024-05-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0013_alter_publication_announcement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photopublication',
            old_name='publications',
            new_name='publication',
        ),
    ]
