# Generated by Django 5.0 on 2024-05-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0014_rename_publications_photopublication_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photopublication',
            old_name='publication',
            new_name='publications',
        ),
    ]
