# Generated by Django 5.0 on 2024-05-20 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_advertisement_preview_image'),
        ('main_page_domer', '0015_rename_publication_photopublication_publications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reasonofcomplaint',
            options={'ordering': ['id'], 'verbose_name': 'Причина жалобы', 'verbose_name_plural': 'Причины жалобы'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.advertisement', verbose_name='Объявление, на которое пожаловались'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.TextField(verbose_name='Обоснование жалобы'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Пользователь, отправивший жалобу'),
        ),
    ]
