# Generated by Django 5.0 on 2024-01-19 15:57

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок элемента')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок поля')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='images', verbose_name='Фото')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='ReasonOfComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(verbose_name='Причина жалобы')),
            ],
            options={
                'verbose_name': 'Причина жалобы',
                'verbose_name_plural': 'Причины жалобы',
            },
        ),
        migrations.CreateModel(
            name='Spisok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок списка')),
            ],
            options={
                'verbose_name': 'Список',
                'verbose_name_plural': 'Списки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок категории')),
                ('type', models.CharField(choices=[('category_1', 'category_1'), ('category_2', 'category_2'), ('category_3', 'category_3'), ('category_4', 'category_4')], max_length=255, verbose_name='Уровень категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.category', verbose_name='Отношения')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('bearer', models.CharField(choices=[('Частное лицо', 'Частное лицо'), ('Компания', 'Компания')], max_length=50, verbose_name='Податель')),
                ('previous_image', models.ImageField(default='default/no_image.jpg', upload_to='images', verbose_name='Предыдущая фотография')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('phone_num', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('moderated', models.BooleanField(default=False, verbose_name='Модерация')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания объявления')),
                ('date_of_deactivate', models.DateTimeField(auto_now=True, verbose_name='Дата деактивации объявления')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный пользователь?)')),
                ('counter_prosmotr', models.IntegerField(blank=True, null=True, verbose_name='Счетчик просмотров')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.category', verbose_name='Раздел')),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.gallery', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Текст комментария')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('moderated', models.CharField(max_length=255)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.advertisement', verbose_name='Связь с объявлением')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='ElementTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Загловок второго элемента')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.element', verbose_name='Связь с элементом')),
            ],
            options={
                'verbose_name': 'Второй элемент',
                'verbose_name_plural': 'Вторые элементы',
            },
        ),
        migrations.CreateModel(
            name='FieldSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок FieldSet')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.category', verbose_name='Связь с категориями')),
                ('fields', models.ManyToManyField(to='advertisement.field', verbose_name='Связь мм с Fields')),
            ],
            options={
                'verbose_name': 'Набор полей',
                'verbose_name_plural': 'Набор полей',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='photos',
            field=models.ManyToManyField(to='advertisement.photo', verbose_name='Связь мм с фотографиями'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Текст с описанием')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('counter_prosmotr', models.IntegerField(blank=True, null=True, verbose_name='Счетчик просмотров')),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.gallery', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст жалобы')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания жалобы')),
                ('user', models.CharField(max_length=255, verbose_name='User')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.advertisement', verbose_name='Объявление')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.reasonofcomplaint', verbose_name='Причина жалобы')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255, verbose_name='Регион, город, район')),
                ('type', models.CharField(choices=[('Область', 'Область'), ('Город', 'Город')], max_length=255, verbose_name='Тип местонахождения')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.region', verbose_name='Отношения')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.region', verbose_name='Регион, город, район'),
        ),
        migrations.AddField(
            model_name='field',
            name='spisok_znach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.spisok', verbose_name='Связь со списком'),
        ),
        migrations.AddField(
            model_name='element',
            name='spisok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.spisok', verbose_name='Связь со списком'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Ссылка с видео')),
                ('logo_image', models.ImageField(blank=True, default='default/no_image.jpg', null=True, upload_to='images', verbose_name='Логотип')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_of_deactivate', models.DateTimeField(auto_now_add=True, verbose_name='Дата деактивации')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный пользователь?)')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('counter_prosmotr', models.IntegerField(verbose_name='Счетчик просмотров')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.category', verbose_name='Связь с категорией')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.region', verbose_name='Связь с регионами')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Связь с User')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
