# Generated by Django 5.0 on 2024-01-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_reasonofcomplaint_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo_image',
            field=models.ImageField(blank=True, default='default/no_image.jpg', null=True, upload_to='images/store_img', verbose_name='Логотип'),
        ),
    ]
