# Generated by Django 5.0 on 2024-05-17 12:10

import advertisement.utils_for_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='preview_image',
            field=models.ImageField(blank=True, default='default/no_image.jpg', null=True, upload_to=advertisement.utils_for_models.upload_to, verbose_name='Главная фотография'),
        ),
    ]
