# Generated by Django 5.0 on 2024-03-26 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='error',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст ошибки при неверно введенных данных'),
        ),
        migrations.AlterField(
            model_name='field',
            name='int_val_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Список числовых значений для задания диапазонов фильтрации'), blank=True, default=list, null=True, size=None),
        ),
    ]
