# Generated by Django 5.0 on 2024-04-24 12:16

import advertisement.utils_for_models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_field_error_alter_field_int_val_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='phone_num',
            field=models.CharField(max_length=255, validators=[users.validators.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='preview_image',
            field=models.ImageField(default='default/no_image.jpg', upload_to=advertisement.utils_for_models.upload_to, verbose_name='Главная фотография'),
        ),
    ]
