# Generated by Django 5.0 on 2024-05-17 14:36

import advertisement.utils_for_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_advertisement_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to=advertisement.utils_for_models.upload_to, verbose_name='Главная фотография'),
        ),
    ]
