# Generated by Django 5.0 on 2024-04-23 16:20

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_field_error_alter_field_int_val_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='phone_num',
            field=models.CharField(max_length=255, validators=[users.validators.validate_phone], verbose_name='Телефон'),
        ),
    ]
