# Generated by Django 5.0 on 2024-03-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_category_keywords_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='keywords_description',
            field=models.CharField(max_length=3000, verbose_name='Meta описание'),
        ),
    ]
