# Generated by Django 5.0 on 2024-01-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_store_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='counter_prosmotr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Счетчик просмотров'),
        ),
    ]
