# Generated by Django 5.0 on 2024-04-26 11:37

import advertisement.utils_for_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_advertisement_phone_num_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photoadvertisement',
            name='photo',
            field=models.ImageField(upload_to=advertisement.utils_for_models.upload_to, verbose_name='Фото'),
        ),
    ]
