# Generated by Django 5.0 on 2024-06-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_advertisement_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения объявления'),
        ),
    ]
