# Generated by Django 5.0 on 2024-02-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_alter_store_category_alter_store_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='store',
            name='contact_name',
            field=models.CharField(max_length=100, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='store',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название магазина'),
        ),
    ]
