# Generated by Django 5.0 on 2024-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_alter_category_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='fav_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок на вкладке'),
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords_description',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Meta описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Главный заголовок'),
        ),
    ]
