# Generated by Django 5.0 on 2024-07-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_uploadfile'),
        ('advertisement', '0005_advertisement_date_of_change'),
    ]

    operations = [
    ]
