# Generated by Django 5.0 on 2024-07-11 12:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_advertisement_date_of_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='additional_information_view',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None), blank=True, null=True, size=None),
        ),
    ]
