# Generated by Django 5.0 on 2024-07-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_advertisement_additional_information_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='title_ad',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок поля'),
        ),
    ]
