# Generated by Django 5.0 on 2024-02-07 13:08

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_advertisement_price_alter_store_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Объявление активно'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Прошло модерацию'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='previous_image',
            field=models.ImageField(default='default/no_image.jpg', upload_to='images', verbose_name='Главная фотография'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.category', verbose_name='Отношение'),
        ),
        migrations.AlterField(
            model_name='region',
            name='area',
            field=models.CharField(max_length=255, verbose_name='Область, город'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.region', verbose_name='Отношение'),
        ),
    ]
