# Generated by Django 5.0 on 2024-03-13 14:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_category_fav_title_alter_category_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='spisok_znach',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AddField(
            model_name='field',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='advertisement.category', verbose_name='Связь с категорией'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='error',
            field=models.CharField(default=None, max_length=500, verbose_name='Текст ошибки при неверно введенных данных'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='int_val_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, verbose_name='Список числовых значений для задания диапазонов фильтрации'), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='max_val_intervel_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимально возможный год для выбора'),
        ),
        migrations.AddField(
            model_name='field',
            name='min_val_intervel_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимально возможный год для выбора'),
        ),
        migrations.AddField(
            model_name='field',
            name='search',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='spisok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.spisok', verbose_name='Связь со списком'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='field',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок поля'),
        ),
    ]
