# Generated by Django 5.0 on 2024-07-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_field_title_ad_alter_field_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='date_of_create',
            field=models.DateTimeField(verbose_name='Дата создания объявления'),
        ),
    ]
