# Generated by Django 5.0 on 2024-03-13 14:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_remove_field_spisok_znach_advertisement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='int_val_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, verbose_name='Список числовых значений для задания диапазонов фильтрации'), default=[], size=None),
        ),
    ]
