# Generated by Django 5.0 on 2024-07-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_alter_advertisement_date_of_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True, verbose_name='URL'),
        ),
    ]
