# Generated by Django 5.0 on 2024-07-21 12:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_alter_advertisement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='additional_information_view',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None), blank=True, editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date_of_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания объявления'),
        ),
    ]
