# Generated by Django 5.0 on 2024-03-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_alter_field_int_val_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='max_val_intervel_date',
            new_name='max_val_interval_date',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='min_val_intervel_date',
            new_name='min_val_interval_date',
        ),
    ]
