# Generated by Django 5.0 on 2024-07-31 11:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_alter_advertisement_additional_information_view_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='advertiseme_search__421054_gin'),
        ),
    ]
