# Generated by Django 5.0 on 2024-03-13 15:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_rename_max_val_intervel_date_field_max_val_interval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='int_val_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Список числовых значений для задания диапазонов фильтрации'), default=list, size=None),
        ),
    ]
