# Generated by Django 5.0 on 2024-07-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_merge_20240703_1506'),
        ('advertisement', '0010_alter_advertisement_additional_information_view_and_more'),
    ]

    operations = [
    ]
