# Generated by Django 5.0 on 2024-07-31 12:40

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_advertisement_search_vector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='title_gin_index', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), name='title_upper_gin_index'),
        ),
    ]
