# Generated by Django 5.0 on 2024-03-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_alter_field_int_val_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.category', verbose_name='Связь с категорией'),
        ),
    ]
