# Generated by Django 5.0 on 2024-07-31 13:27

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0012_alter_advertisement_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='search_title_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
