# Generated by Django 5.0 on 2024-07-24 15:30

import advertisement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0012_errorfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorfile',
            options={'verbose_name': 'Файл с объявлениями с ошибками', 'verbose_name_plural': 'Файлы с объявлениями с ошибками'},
        ),
        migrations.AddField(
            model_name='errorfile',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус скачен файл или нет'),
        ),
        migrations.AlterField(
            model_name='errorfile',
            name='file',
            field=models.FilePathField(verbose_name='Путь к файлу с объявлениями с ошибками'),
        ),
        migrations.AlterField(
            model_name='errorfile',
            name='time_upload_file',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания файла'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=advertisement.models.UploadFile.get, verbose_name='Путь к файлу с объявлениями'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='time_upload_file',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки файла'),
        ),
    ]
