# Generated by Django 5.0 on 2024-07-31 13:35

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0013_advertisement_search_title_vector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advertisement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_title_vector'], name='advertiseme_search__07fa62_gin'),
        ),
    ]
