# Generated by Django 5.0 on 2024-07-30 15:08

import advertisement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0013_alter_errorfile_options_errorfile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorfile',
            name='file',
            field=models.FileField(upload_to=advertisement.models.ErrorFile.get, verbose_name='Путь к файлу с объявлениями с ошибками'),
        ),
        migrations.AlterField(
            model_name='errorfile',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Был доступ у пользователя к файлу или нет'),
        ),
    ]
