# Generated by Django 5.0 on 2024-07-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0014_alter_errorfile_file_alter_errorfile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorfile',
            name='file',
        ),
    ]
