# Generated by Django 5.0 on 2024-08-02 09:02

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0014_advertisement_advertiseme_search__07fa62_gin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advertisement',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['date_of_create'], name='advertiseme_date_of_2c3be1_brin'),
        ),
    ]
