# Generated by Django 5.0 on 2024-08-02 09:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0015_advertisement_advertiseme_date_of_2c3be1_brin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='search_similar',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_similar'], name='advertiseme_search__106612_gin'),
        ),
    ]
