# Generated by Django 5.0 on 2024-07-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0015_remove_errorfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorfile',
            name='file',
            field=models.CharField(default=2, max_length=255, verbose_name='Путь к файлу с объявлениями с ошибками'),
            preserve_default=False,
        ),
    ]
