# Generated by Django 5.0 on 2024-08-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0016_advertisement_search_similar_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='advertisement',
            name='advertiseme_search__106612_gin',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='search_similar',
        ),
    ]
