# Generated by Django 5.0 on 2024-07-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0016_errorfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorfile',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к файлу с объявлениями с ошибками'),
        ),
    ]
