# Generated by Django 5.0 on 2024-08-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0017_remove_advertisement_advertiseme_search__106612_gin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Элемент для списка', 'verbose_name_plural': 'Элементы для списка'},
        ),
        migrations.AlterModelOptions(
            name='elementtwo',
            options={'verbose_name': 'Дополнительный элемент для списка', 'verbose_name_plural': 'Дополнительные элементы для списка'},
        ),
        migrations.AlterModelOptions(
            name='spisok',
            options={'verbose_name': 'Список элементов для полей', 'verbose_name_plural': 'Списки элементов для полей'},
        ),
    ]
