# Generated by Django 5.0 on 2024-07-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0017_alter_errorfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorfile',
            name='file',
            field=models.CharField(max_length=255, verbose_name='Путь к файлу с объявлениями с ошибками'),
        ),
    ]
