# Generated by Django 5.0 on 2024-08-05 17:30

import advertisement.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0018_alter_errorfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Нецензурное слово',
                'verbose_name_plural': 'Нецензурные слова',
            },
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='contact_name',
            field=models.CharField(max_length=255, validators=[advertisement.validators.validate_words], verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(validators=[advertisement.validators.validate_words], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=255, validators=[advertisement.validators.validate_words], verbose_name='Заголовок'),
        ),
    ]
