# Generated by Django 5.0 on 2024-08-10 17:43

import advertisement.utils_for_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0018_alter_element_options_alter_elementtwo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoadvertisement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=advertisement.utils_for_models.upload_to, verbose_name='Фото'),
        ),
    ]
