# Generated by Django 5.0 on 2024-08-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0018_alter_element_options_alter_elementtwo_options_and_more'),
        ('advertisement', '0019_badwords_alter_advertisement_contact_name_and_more'),
    ]

    operations = [
    ]
