# Generated by Django 5.0 on 2024-08-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0019_alter_photoadvertisement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone_num',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
