# Generated by Django 5.0 on 2024-08-07 17:20

import advertisement.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0020_merge_20240807_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(db_index=True, max_length=255, validators=[advertisement.validators.validate_words], verbose_name='Заголовок'),
        ),
    ]
