# Generated by Django 5.0 on 2024-08-11 15:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0020_alter_store_phone_num'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='store',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='advertiseme_search__f69d65_gin'),
        ),
    ]
