# Generated by Django 5.0 on 2024-08-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0019_alter_photoadvertisement_photo'),
        ('advertisement', '0021_alter_advertisement_title'),
    ]

    operations = [
    ]
